# Just to get /usr/bin/qemu-arm-static
FROM ubuntu:18.04
RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends qemu-user-static

# Build actual image
FROM arm32v7/ubuntu:18.04

COPY --from=0 /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static

COPY docker/build.sh /build.sh
COPY docker/entrypoint.sh /entrypoint.sh

RUN /build.sh

EXPOSE 8332 8333

ENTRYPOINT ["/entrypoint.sh"]
