FROM arm32v7/ubuntu:18.04

COPY /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static

COPY docker/build.sh /build.sh
COPY docker/entrypoint.sh /entrypoint.sh

RUN /build.sh

EXPOSE 8332 8333

ENTRYPOINT ["/entrypoint.sh"]
